// Dados completos dos Pokémon para geração das páginas de detalhes
const pokemonData = [
    { id: 1, name: "Bulbasaur", type: ["grass", "poison"], description: "Um Pokémon do tipo Grama/Veneno. É conhecido por sua natureza calma e por carregar uma semente em suas costas." },
    { id: 2, name: "Ivysaur", type: ["grass", "poison"], description: "A evolução de Bulbasaur. O botão em suas costas cresce e libera um aroma doce que melhora as emoções." },
    { id: 3, name: "Venusaur", type: ["grass", "poison"], description: "A evolução final de Bulbasaur. Sua flor libera um aroma calmante que melhora o humor das pessoas." },
    { id: 4, name: "Charmander", type: ["fire"], description: "Um Pokémon do tipo Fogo. A chama em sua cauda indica sua saúde e emoções." },
    { id: 5, name: "Charmeleon", type: ["fire"], description: "A evolução de Charmander. Tem uma natureza selvagem e adora lutar." },
    { id: 6, name: "Charizard", type: ["fire", "flying"], description: "A evolução final de Charmander. Pode voar até 1.400 metros de altura." },
    { id: 7, name: "Squirtle", type: ["water"], description: "Um Pokémon do tipo Água. Pode se retrair em seu casco para proteção." },
    { id: 8, name: "Wartortle", type: ["water"], description: "A evolução de Squirtle. Sua cauda peluda escurece com a idade." },
    { id: 9, name: "Blastoise", type: ["water"], description: "A evolução final de Squirtle. Possui canhões d'água em seu casco." },
    { id: 10, name: "Caterpie", type: ["bug"], description: "Um Pokémon do tipo Inseto. Tem um apetite voraz e pode comer folhas maiores que seu corpo." },
    { id: 11, name: "Metapod", type: ["bug"], description: "A evolução de Caterpie. Seu corpo endurece em preparação para a evolução." },
    { id: 12, name: "Butterfree", type: ["bug", "flying"], description: "A evolução final de Caterpie. Suas asas coloridas são cobertas por escamas venenosas." },
    { id: 13, name: "Weedle", type: ["bug", "poison"], description: "Um pequeno Pokémon inseto com um ferrão venenoso na cabeça." },
    { id: 14, name: "Kakuna", type: ["bug", "poison"], description: "A evolução de Weedle. Permanece imóvel enquanto se prepara para evoluir." },
    { id: 15, name: "Beedrill", type: ["bug", "poison"], description: "A evolução final de Weedle. Seus ferrões são extremamente venenosos." },
    { id: 16, name: "Pidgey", type: ["normal", "flying"], description: "Um Pokémon pássaro comum que pode ser encontrado em florestas e campos." },
    { id: 17, name: "Pidgeotto", type: ["normal", "flying"], description: "A evolução de Pidgey. Tem território próprio e defende-o ferozmente." },
    { id: 18, name: "Pidgeot", type: ["normal", "flying"], description: "A evolução final de Pidgey. Suas penas coloridas são lindas de se ver." },
    { id: 19, name: "Rattata", type: ["normal"], description: "Um pequeno Pokémon roedor que pode ser encontrado em qualquer lugar." },
    { id: 20, name: "Raticate", type: ["normal"], description: "A evolução de Rattata. Seus dentes crescem continuamente durante toda a vida." },
    { id: 21, name: "Spearow", type: ["normal", "flying"], description: "Um pequeno Pokémon pássaro com temperamento agressivo." },
    { id: 22, name: "Fearow", type: ["normal", "flying"], description: "A evolução de Spearow. Suas asas enormes nunca se cansam." },
    { id: 23, name: "Ekans", type: ["poison"], description: "Um Pokémon serpente que se move silenciosamente pela grama." },
    { id: 24, name: "Arbok", type: ["poison"], description: "A evolução de Ekans. O padrão em seu peito intimida os inimigos." },
    { id: 25, name: "Pikachu", type: ["electric"], description: "O Pokémon mais famoso do mundo. Armazena eletricidade em suas bochechas." },
    { id: 26, name: "Raichu", type: ["electric"], description: "A evolução de Pikachu. Pode descarregar 100.000 volts de eletricidade." },
    { id: 27, name: "Sandshrew", type: ["ground"], description: "Um Pokémon do tipo Terra que vive em áreas desérticas." },
    { id: 28, name: "Sandslash", type: ["ground"], description: "A evolução de Sandshrew. Suas garras são afiadas como navalhas." },
    { id: 29, name: "Nidoran♀", type: ["poison"], description: "A versão fêmea de Nidoran. Pequena mas com espinhos venenosos." },
    { id: 30, name: "Nidorina", type: ["poison"], description: "A evolução de Nidoran♀. Mais dócil que sua pré-evolução." },
    { id: 31, name: "Nidoqueen", type: ["poison", "ground"], description: "A evolução final de Nidoran♀. Protege ferozmente seus filhotes." },
    { id: 32, name: "Nidoran♂", type: ["poison"], description: "A versão macho de Nidoran. Mais agressivo que a fêmea." },
    { id: 33, name: "Nidorino", type: ["poison"], description: "A evolução de Nidoran♂. Facilmente irritável e sempre pronto para lutar." },
    { id: 34, name: "Nidoking", type: ["poison", "ground"], description: "A evolução final de Nidoran♂. Sua pele é dura como diamante." },
    { id: 35, name: "Clefairy", type: ["fairy"], description: "Um Pokémon fada adorável que dança sob a luz da lua." },
    { id: 36, name: "Clefable", type: ["fairy"], description: "A evolução de Clefairy. Raramente é visto por humanos." },
    { id: 37, name: "Vulpix", type: ["fire"], description: "Um Pokémon raposa com seis caudas lindas e encaracoladas." },
    { id: 38, name: "Ninetales", type: ["fire"], description: "A evolução de Vulpix. Diz-se que vive por 1.000 anos." },
    { id: 39, name: "Jigglypuff", type: ["normal", "fairy"], description: "Um Pokémon que canta canções de ninar que fazem todos dormirem." },
    { id: 40, name: "Wigglytuff", type: ["normal", "fairy"], description: "A evolução de Jigglypuff. Sua pele é extremamente macia." },
    { id: 41, name: "Zubat", type: ["poison", "flying"], description: "Um Pokémon morcego que vive em cavernas escuras." },
    { id: 42, name: "Golbat", type: ["poison", "flying"], description: "A evolução de Zubat. Suga sangue com suas presas afiadas." },
    { id: 43, name: "Oddish", type: ["grass", "poison"], description: "Um Pokémon planta que se enterra no solo durante o dia." },
    { id: 44, name: "Gloom", type: ["grass", "poison"], description: "A evolução de Oddish. Libera um odor terrível de sua boca." },
    { id: 45, name: "Vileplume", type: ["grass", "poison"], description: "A evolução de Gloom. Suas pétalas são as maiores do mundo." },
    { id: 46, name: "Paras", type: ["bug", "grass"], description: "Um Pokémon com cogumelos parasitas crescendo em suas costas." },
    { id: 47, name: "Parasect", type: ["bug", "grass"], description: "A evolução de Paras. O cogumelo controla completamente seu corpo." },
    { id: 48, name: "Venonat", type: ["bug", "poison"], description: "Um Pokémon inseto com olhos compostos grandes." },
    { id: 49, name: "Venomoth", type: ["bug", "poison"], description: "A evolução de Venonat. Suas asas liberam escamas venenosas." },
    { id: 50, name: "Diglett", type: ["ground"], description: "Um Pokémon toupeira que vive no subsolo." },
    { id: 51, name: "Dugtrio", type: ["ground"], description: "A evolução de Diglett. Três Diglett unidos como um." },
    { id: 52, name: "Meowth", type: ["normal"], description: "Um Pokémon gato que adora objetos brilhantes." },
    { id: 53, name: "Persian", type: ["normal"], description: "A evolução de Meowth. Move-se com graça e elegância." },
    { id: 54, name: "Psyduck", type: ["water"], description: "Um Pokémon pato que sofre de dores de cabeça constantes." },
    { id: 55, name: "Golduck", type: ["water"], description: "A evolução de Psyduck. Possui poderes psíquicos poderosos." },
    { id: 56, name: "Mankey", type: ["fighting"], description: "Um Pokémon macaco extremamente agressivo e temperamental." },
    { id: 57, name: "Primeape", type: ["fighting"], description: "A evolução de Mankey. Fica furioso por qualquer motivo." },
    { id: 58, name: "Growlithe", type: ["fire"], description: "Um Pokémon cão leal e corajoso." },
    { id: 59, name: "Arcanine", type: ["fire"], description: "A evolução de Growlithe. Conhecido como um Pokémon lendário." },
    { id: 60, name: "Poliwag", type: ["water"], description: "Um Pokémon girino com uma espiral transparente na barriga." },
    { id: 61, name: "Poliwhirl", type: ["water"], description: "A evolução de Poliwag. A espiral em sua barriga gira hipnoticamente." },
    { id: 62, name: "Poliwrath", type: ["water", "fighting"], description: "Uma das evoluções de Poliwhirl. Nadador poderoso." },
    { id: 63, name: "Abra", type: ["psychic"], description: "Um Pokémon psíquico que dorme 18 horas por dia." },
    { id: 64, name: "Kadabra", type: ["psychic"], description: "A evolução de Abra. Emite ondas psíquicas de sua cabeça." },
    { id: 65, name: "Alakazam", type: ["psychic"], description: "A evolução final de Abra. Seu cérebro nunca para de crescer." },
    { id: 66, name: "Machop", type: ["fighting"], description: "Um Pokémon lutador que treina constantemente." },
    { id: 67, name: "Machoke", type: ["fighting"], description: "A evolução de Machop. Usa um cinto para controlar sua força." },
    { id: 68, name: "Machamp", type: ["fighting"], description: "A evolução final de Machop. Seus quatro braços podem dar 1.000 socos por segundo." },
    { id: 69, name: "Bellsprout", type: ["grass", "poison"], description: "Um Pokémon planta carnívora com corpo flexível." },
    { id: 70, name: "Weepinbell", type: ["grass", "poison"], description: "A evolução de Bellsprout. Usa suas folhas como navalhas." },
    { id: 71, name: "Victreebel", type: ["grass", "poison"], description: "A evolução final de Bellsprout. Atrai presas com seu aroma doce." },
    { id: 72, name: "Tentacool", type: ["water", "poison"], description: "Um Pokémon água-viva com tentáculos venenosos." },
    { id: 73, name: "Tentacruel", type: ["water", "poison"], description: "A evolução de Tentacool. Seus 80 tentáculos podem se estender livremente." },
    { id: 74, name: "Geodude", type: ["rock", "ground"], description: "Um Pokémon rocha que parece uma pedra comum." },
    { id: 75, name: "Graveler", type: ["rock", "ground"], description: "A evolução de Geodude. Rola montanha abaixo para se mover." },
    { id: 76, name: "Golem", type: ["rock", "ground"], description: "A evolução final de Geodude. Seu corpo é duro como rocha." },
    { id: 77, name: "Ponyta", type: ["fire"], description: "Um Pokémon cavalo com crina de fogo." },
    { id: 78, name: "Rapidash", type: ["fire"], description: "A evolução de Ponyta. Pode correr a 240 km/h." },
    { id: 79, name: "Slowpoke", type: ["water", "psychic"], description: "Um Pokémon lento que pesca com sua cauda." },
    { id: 80, name: "Slowbro", type: ["water", "psychic"], description: "A evolução de Slowpoke. Um Shellder morde sua cauda." },
    { id: 81, name: "Magnemite", type: ["electric", "steel"], description: "Um Pokémon magnético que flutua no ar." },
    { id: 82, name: "Magneton", type: ["electric", "steel"], description: "A evolução de Magnemite. Três Magnemite unidos por magnetismo." },
    { id: 83, name: "Farfetch'd", type: ["normal", "flying"], description: "Um Pokémon pato que sempre carrega um alho-poró." },
    { id: 84, name: "Doduo", type: ["normal", "flying"], description: "Um Pokémon pássaro com duas cabeças." },
    { id: 85, name: "Dodrio", type: ["normal", "flying"], description: "A evolução de Doduo. Suas três cabeças representam emoções diferentes." },
    { id: 86, name: "Seel", type: ["water"], description: "Um Pokémon foca que adora águas geladas." },
    { id: 87, name: "Dewgong", type: ["water", "ice"], description: "A evolução de Seel. Seu corpo é coberto por pele grossa." },
    { id: 88, name: "Grimer", type: ["poison"], description: "Um Pokémon feito de lodo tóxico." },
    { id: 89, name: "Muk", type: ["poison"], description: "A evolução de Grimer. Seu corpo é extremamente venenoso." },
    { id: 90, name: "Shellder", type: ["water"], description: "Um Pokémon bivalve que se fecha quando atacado." },
    { id: 91, name: "Cloyster", type: ["water", "ice"], description: "A evolução de Shellder. Sua concha é mais dura que diamante." },
    { id: 92, name: "Gastly", type: ["ghost", "poison"], description: "Um Pokémon fantasma feito de gás venenoso." },
    { id: 93, name: "Haunter", type: ["ghost", "poison"], description: "A evolução de Gastly. Esconde-se na escuridão e congela suas vítimas." },
    { id: 94, name: "Gengar", type: ["ghost", "poison"], description: "A evolução final de Gastly. Um Pokémon fantasma travesso que se esconde nas sombras." },
    { id: 95, name: "Onix", type: ["rock", "ground"], description: "Um Pokémon serpente gigante feito de rochas." },
    { id: 96, name: "Drowzee", type: ["psychic"], description: "Um Pokémon que se alimenta de sonhos." },
    { id: 97, name: "Hypno", type: ["psychic"], description: "A evolução de Drowzee. Hipnotiza suas vítimas com seu pêndulo." },
    { id: 98, name: "Krabby", type: ["water"], description: "Um Pokémon caranguejo que vive perto da água." },
    { id: 99, name: "Kingler", type: ["water"], description: "A evolução de Krabby. Sua garra gigante tem força esmagadora." },
    { id: 100, name: "Voltorb", type: ["electric"], description: "Um Pokémon que se parece com uma Poké Ball." },
    { id: 101, name: "Electrode", type: ["electric"], description: "A evolução de Voltorb. Explode ao menor toque." },
    { id: 102, name: "Exeggcute", type: ["grass", "psychic"], description: "Um grupo de seis ovos que se comunicam telepaticamente." },
    { id: 103, name: "Exeggutor", type: ["grass", "psychic"], description: "A evolução de Exeggcute. Suas três cabeças pensam independentemente." },
    { id: 104, name: "Cubone", type: ["ground"], description: "Um Pokémon órfão que usa o crânio de sua mãe como capacete." },
    { id: 105, name: "Marowak", type: ["ground"], description: "A evolução de Cubone. Dominou sua tristeza e se tornou mais forte." },
    { id: 106, name: "Hitmonlee", type: ["fighting"], description: "Um Pokémon lutador especializado em chutes." },
    { id: 107, name: "Hitmonchan", type: ["fighting"], description: "Um Pokémon lutador especializado em socos." },
    { id: 108, name: "Lickitung", type: ["normal"], description: "Um Pokémon com uma língua extremamente longa." },
    { id: 109, name: "Koffing", type: ["poison"], description: "Um Pokémon que libera gases tóxicos de seu corpo." },
    { id: 110, name: "Weezing", type: ["poison"], description: "A evolução de Koffing. Dois Koffing unidos que compartilham gases." },
    { id: 111, name: "Rhyhorn", type: ["ground", "rock"], description: "Um Pokémon rinoceronte com pele dura como rocha." },
    { id: 112, name: "Rhydon", type: ["ground", "rock"], description: "A evolução de Rhyhorn. Pode perfurar diamantes com seu chifre." },
    { id: 113, name: "Chansey", type: ["normal"], description: "Um Pokémon gentil que compartilha seus ovos nutritivos." },
    { id: 114, name: "Tangela", type: ["grass"], description: "Um Pokémon coberto por vinhas azuis." },
    { id: 115, name: "Kangaskhan", type: ["normal"], description: "Um Pokémon canguru que protege seu filhote na bolsa." },
    { id: 116, name: "Horsea", type: ["water"], description: "Um pequeno Pokémon cavalo-marinho." },
    { id: 117, name: "Seadra", type: ["water"], description: "A evolução de Horsea. Seus espinhos são extremamente venenosos." },
    { id: 118, name: "Goldeen", type: ["water"], description: "Um Pokémon peixe dourado muito elegante." },
    { id: 119, name: "Seaking", type: ["water"], description: "A evolução de Goldeen. Usa seu chifre para fazer ninhos." },
    { id: 120, name: "Staryu", type: ["water"], description: "Um Pokémon estrela-do-mar com um núcleo vermelho." },
    { id: 121, name: "Starmie", type: ["water", "psychic"], description: "A evolução de Staryu. Seu núcleo brilha com sete cores." },
    { id: 122, name: "Mr. Mime", type: ["psychic", "fairy"], description: "Um Pokémon mímico que cria barreiras invisíveis." },
    { id: 123, name: "Scyther", type: ["bug", "flying"], description: "Um Pokémon louva-a-deus com lâminas afiadas." },
    { id: 124, name: "Jynx", type: ["ice", "psychic"], description: "Um Pokémon humanóide que dança de forma hipnótica." },
    { id: 125, name: "Electabuzz", type: ["electric"], description: "Um Pokémon elétrico que adora tempestades." },
    { id: 126, name: "Magmar", type: ["fire"], description: "Um Pokémon de fogo que vive perto de vulcões." },
    { id: 127, name: "Pinsir", type: ["bug"], description: "Um Pokémon besouro com pinças poderosas." },
    { id: 128, name: "Tauros", type: ["normal"], description: "Um Pokémon touro selvagem e temperamental." },
    { id: 129, name: "Magikarp", type: ["water"], description: "Um Pokémon peixe considerado o mais fraco de todos." },
    { id: 130, name: "Gyarados", type: ["water", "flying"], description: "A evolução de Magikarp. Um dos Pokémon mais ferozes." },
    { id: 131, name: "Lapras", type: ["water", "ice"], description: "Um Pokémon gentil que transporta pessoas em suas costas." },
    { id: 132, name: "Ditto", type: ["normal"], description: "Um Pokémon que pode se transformar em qualquer coisa." },
    { id: 133, name: "Eevee", type: ["normal"], description: "Um Pokémon com DNA instável que pode evoluir de várias formas." },
    { id: 134, name: "Vaporeon", type: ["water"], description: "Uma das evoluções de Eevee. Pode se dissolver na água." },
    { id: 135, name: "Jolteon", type: ["electric"], description: "Uma das evoluções de Eevee. Seus espinhos disparam raios." },
    { id: 136, name: "Flareon", type: ["fire"], description: "Uma das evoluções de Eevee. Sua temperatura corporal chega a 900°C." },
    { id: 137, name: "Porygon", type: ["normal"], description: "Um Pokémon artificial criado por computador." },
    { id: 138, name: "Omanyte", type: ["rock", "water"], description: "Um Pokémon fóssil que viveu nos oceanos antigos." },
    { id: 139, name: "Omastar", type: ["rock", "water"], description: "A evolução de Omanyte. Usava seus tentáculos para capturar presas." },
    { id: 140, name: "Kabuto", type: ["rock", "water"], description: "Um Pokémon fóssil que viveu no fundo do mar." },
    { id: 141, name: "Kabutops", type: ["rock", "water"], description: "A evolução de Kabuto. Nadava rapidamente para caçar presas." },
    { id: 142, name: "Aerodactyl", type: ["rock", "flying"], description: "Um Pokémon fóssil que dominava os céus na era pré-histórica." },
    { id: 143, name: "Snorlax", type: ["normal"], description: "Um Pokémon gigante que passa a maior parte do tempo dormindo." },
    { id: 144, name: "Articuno", type: ["ice", "flying"], description: "Um Pokémon lendário pássaro do gelo." },
    { id: 145, name: "Zapdos", type: ["electric", "flying"], description: "Um Pokémon lendário pássaro do trovão." },
    { id: 146, name: "Moltres", type: ["fire", "flying"], description: "Um Pokémon lendário pássaro do fogo." },
    { id: 147, name: "Dratini", type: ["dragon"], description: "Um Pokémon dragão que vive em lagos limpos." },
    { id: 148, name: "Dragonair", type: ["dragon"], description: "A evolução de Dratini. Controla o clima com suas esferas." },
    { id: 149, name: "Dragonite", type: ["dragon", "flying"], description: "A evolução final de Dratini. Pode dar a volta ao mundo em 16 horas." },
    { id: 150, name: "Mewtwo", type: ["psychic"], description: "Um Pokémon lendário criado através de manipulação genética. Possui poderes psíquicos incríveis." },
    { id: 151, name: "Mew", type: ["psychic"], description: "Um Pokémon mítico que possui o DNA de todos os Pokémon. Pode aprender qualquer movimento." }
];

// Função para obter dados de um Pokémon por ID
function getPokemonById(id) {
    const pokemon = pokemonData.find(p => p.id === id);
    if (pokemon) {
        return pokemon;
    }
    
    // Fallback para Pokémon não listados
    return {
        id: id,
        name: `Pokemon #${id.toString().padStart(3, '0')}`,
        type: ["normal"],
        description: `Informações detalhadas sobre este Pokémon #${id}.`
    };
}

// Função para gerar URL das imagens
function getPokemonImageUrls(id) {
    const paddedId = id.toString().padStart(3, '0');
    return {
        official: `https://assets.pokemon.com/assets/cms2/img/pokedex/full/${paddedId}.png`,
        normalGif: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/${id}.gif`,
        shinyGif: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/shiny/${id}.gif`,
        sprite: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`,
        shinySprite: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/${id}.png`
    };
}

// Cores dos tipos
const typeColors = {
    normal: '#A8A878',
    fire: '#F08030',
    water: '#6890F0',
    electric: '#F8D030',
    grass: '#78C850',
    ice: '#98D8D8',
    fighting: '#C03028',
    poison: '#A040A0',
    ground: '#E0C068',
    flying: '#A890F0',
    psychic: '#F85888',
    bug: '#A8B820',
    rock: '#B8A038',
    ghost: '#705898',
    dragon: '#7038F8',
    dark: '#705848',
    steel: '#B8B8D0',
    fairy: '#EE99AC'
};

// Disponibilizar globalmente
window.pokemonData = pokemonData;
window.getPokemonById = getPokemonById;
window.getPokemonImageUrls = getPokemonImageUrls;
window.typeColors = typeColors;

